grails:
    plugin:
        springsecurity:
            saml:
                userAttributeMappings: {}
                active: false
                afterLoginUrl: '/'
                afterLogoutUrl: '/'
                userGroupAttribute: 'memberOf'
                responseSkew: 60
                autoCreate:
                    active: false
                    key: 'username'
                    assignAuthorities: true
                metadata:
                    timeout: 5000
                    defaultIdp: ''
                    url: '/saml/metadata'
                    providers: {}
                    sp:
                        file: 'security/sp.xml'
                        defaults:
                            local: true
                            alias: 'test'
                            securityProfile: 'metaiop'
                            signingKey: 'ping'
                            encryptionKey: 'ping'
                            tlsKey: 'ping'
                            requireArtifactResolveSigned: false
                            requireLogoutRequestSigned: false
                            requireLogoutResponseSigned: false
                keyManager:
                    storeFile: 'classpath:security/keystore.jks'
                    storePass: 'nalle123'
                    passwords:
                        ping: 'ping123'
                    defaultKey: 'ping'
